### ISSUE TITLE
Doesn't work with GitHub actions

### ISSUE THREAD

**Issue by gg2001** [ItsNickBarry/hardhat-dependency-compiler#4]
This works fine on my local machine, but fails when I run my tests on GitHub actions:

```
yarn run v1.17.3
$ hardhat typechain
An unexpected error occurred:

{ Error: ENOTEMPTY: directory not empty, rmdir '/github/workspace/contracts/hardhat-dependency-compiler'
    at Object.rmdirSync (fs.js:684:3)
    at OverriddenTaskDefinition._action (/github/workspace/node_modules/hardhat-dependency-compiler/index.js:48:10)
    at Environment._runTaskDefinition (/github/workspace/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:35)
    at Environment.run (/github/workspace/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:25)
    at SimpleTaskDefinition.config_1.task.setAction [as action] (/github/workspace/node_modules/@typechain/hardhat/src/index.ts:58:9)
    at Environment._runTaskDefinition (/github/workspace/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:35)
    at Environment.run (/github/workspace/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:25)
    at main (/github/workspace/node_modules/hardhat/src/internal/cli/cli.ts:188:15)
  errno: -39,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: '/github/workspace/contracts/hardhat-dependency-compiler' }
error Command failed with exit code 1.
```

**Comment by ItsNickBarry** [comment]
What node version does GitHub actions use?

**Comment by ItsNickBarry** [comment]
Seems like the same issue as described here: https://github.com/ItsNickBarry/hardhat-abi-exporter/issues/5

However, the `package.json` attempts to avoid the error by enforcing a compatible Node version: https://github.com/ItsNickBarry/hardhat-dependency-compiler/blob/46a1aabf7440ab72e996389450300099b0f65dc1/package.json#L31-L33

Not sure what's going on, will reopen if it comes up again with more information.
